name: 'NPM Pack Check'
description: 'Builds JS distribution, performs an npm pack dry-run, and asserts package payload'

runs:
  using: 'composite'
  steps:
    - name: Build JS Distribution
      run: npm run build
      shell: bash

    - name: NPM Pack Dry Run
      run: npm pack --dry-run
      shell: bash

    - name: Assert Package Payload
      run: npm run test:pack
      shell: bash
