name: Deploy Web Studio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Ensure this job only runs if CI successfully builds the artifacts
    needs: [build-web]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-builds
          path: web/dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/dist
          branch: gh-pages
